apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "application.name" . }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/instance: {{ .Values.environment }}
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: {{ template "application.name" . }}
    app.kubernetes.io/managed-by: {{ .Values.managedBy }}
data:
  BASE_URL: {{ .Values.baseUrl | quote }}
  MERINO_ENV: "production"
  MERINO_METRICS__HOST: {{ .Values.telegrafStatsdHost | quote }}
  MERINO_METRICS__PORT: {{ .Values.telegrafStatsdPort | quote }}
  MERINO_SENTRY__ENV: {{ .Values.sentryEnvironment | quote }}
  MERINO_SENTRY__DSN: {{ .Values.sentryDsn | quote }}
  MERINO_SENTRY__MODE: "release"
  PORT: "8000"
