apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "application.name" . }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/instance: {{ .Values.environment }}
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: {{ template "application.name" . }}
    app.kubernetes.io/managed-by: {{ .Values.managedBy }}
spec:
  redirectToHttps:
    enabled: false
    responseCodeName: FOUND
  sslPolicy: mozilla-intermediate
