{{- if .Values.ingressEnabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "application.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "application.name" . }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/instance: {{ .Values.environment }}
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: {{ template "application.name" . }}
    app.kubernetes.io/managed-by: {{ .Values.managedBy }}
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: {{ template "application.fullname" . }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingressStaticIpName }}
    ingress.gcp.kubernetes.io/pre-shared-cert: {{ .Values.ingressCertName }}
spec:
  defaultBackend:
    service:
      name: {{ .Values.appService }}
      port:
        number: {{ .Values.appServicePort }}
{{- end }}
