apiVersion: apps/v1
kind: Deployment
metadata:
  name: merino
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: merino
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: merino
    spec:
      terminationGracePeriodSeconds: 5
      volumes:
        - name: providers
          configMap:
            name: merino-providers
      containers:
        - name: merino
          image: mozilla/merino:prod-a1276886f04185e81b8a61c252bbeb2d3e7b28bd
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 8000
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "25"]
          livenessProbe:
            httpGet:
              path: /__lbheartbeat__
              port: app
            periodSeconds: 6
            timeoutSeconds: 5
            failureThreshold: 5
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /__lbheartbeat__
              port: app
            periodSeconds: 6
            timeoutSeconds: 5
            initialDelaySeconds: 10
          envFrom:
            - configMapRef:
                name: merino
          volumeMounts:
            - name: providers
              mountPath: /app/config/providers/local.yaml
              subPath: local.yaml
              readOnly: true
          resources:
            limits:
              cpu: 1.5
            requests:
              cpu: 1
