apiVersion: v1
kind: Service
metadata:
  name: merino
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: merino
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
