apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyrino
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: pyrino
  template:
    metadata:
      name: pyrino
      labels:
        app.kubernetes.io/name: pyrino
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/wstuckey-sandbox/pyrino-repo/pyrino
        name: pyrino
        resources:
          limits:
            cpu: 1.5
          requests:
            cpu: 1
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
          - name: PORT
            value: "8080"

---
# kubernetes-fastapi LoadBalancer Service
# Enables the pods in a deployment to be accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: pyrino
spec:
  selector:
    app.kubernetes.io/name: pyrino
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer

