apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyrino
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: pyrino
  template:
    metadata:
      name: pyrino
      labels:
        app.kubernetes.io/name: pyrino
    spec:
      containers:
      - name: pyrino
        image: us-central1-docker.pkg.dev/wstuckey-sandbox/pyrino-repo/pyrino:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1.5
          requests:
            cpu: 1
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
          - name: PORT
            value: "8080"

